### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by Karolinehc** [rayjolt/hugo-multilingual-example#1] opened 2017-08-22 01:10 UTC
Hey there! thanks for this post about multilingual, I would like to know if I have misunderstood something because I couldn't test your multilingual example I typed the following Hugo's command line I'm window's user:
I cloned the git// etc.........multilingual-example
cd Hugo-multilingual-example
hugo.exe --buildDrafts
it created the public folder but not theme's folder so I created the manual's way
into of the Theme's folder, I cloned any theme from Hugo 
and then I typed 
"hugo.exe server -t "name theme" and I couldn't watch your example.
Do you have some specific theme which Can I test your example? please! 
Have I done some mistake?
:)

**Comment by rayjolt** [comment] 2017-08-22 10:07
Hi, and thanks for trying out my repo!

I need a few more pieces of information to figure out what's going wrong with your setup. First, what version of Hugo are you using? Second, what theme did you try it with? And third, can you write all of the commands that you tried, exactly as you typed them? I don't have Windows on my computer so I can't test your exact environment, but with that information I should hopefully be able to figure out what the problem is.

As for a specific theme you can try, I've tested it with halogenica/beautifulhugo, so that should work. It should work with most themes though, as long as you configure the theme properly. (Whether the theme has proper multilingual support is another question, though.)

**Comment by rayjolt** [comment] 2017-08-31 14:17
I'm marking this as closed, as it sounds like it's something to do with your setup rather than a problem with the code itself. If you give me the details I asked for above, though, I can probably help you to figure out what's wrong.

**Closed as completed by rayjolt** 2017-08-31 14:17 UTC

**Comment by Karolinehc** [comment] 2017-08-31 14:41
So sorry I'm late for the answer it has worked with the halogenica/beautifulhugo perfectly.

I'm interested to try it with another theme from Hugo but it will be the weekend or the next week anyway I imagine that I should study what're the special characteristics from halogenica/beautifulhugo or what're the special configurations that any theme from Hugo should have for that your multi languages example works perfectly. 

When I tried it the first time I took introduction theme, the idea is repeating the exercise with it or differents themes so that I will tell you :) thank you Rayjolt

**Comment by Karolinehc** [comment] 2017-09-21 02:59
Hello Rayjolt ;) I have been re-reading (studying) your blog and watching the code from beautiful hugo and your example called "Hugo multi example" and I have some questions such as 👍 

1. you said that it just has three languages setup I can't  add more than it? ..... (I saw more than on i18n folder)

2. On yaml config folder i18n there are de.yaml, en.yaml etc but I didn't see fr.yaml and it is set up ( for French language ) How can it be possible :) :) :)

3) hard code strings is for example "next post" , "newer posts" etc  for #content #404 page etc???? ( you said to pass hard string code to i18n folder) 
Thank you very much!!

**Comment by rayjolt** [comment] 2017-10-05 13:46
Hi, and sorry for the late reply.
1. You can add as many languages as you want. Hugo doesn't have a language limit - you just add the config to your config.toml, add the translation file, and that should be it.
2. You just create it, and add the content. There's no magic command to generate it or anything.
3. Yep, that's exactly right.

**Comment by Karolinehc** [comment] 2017-11-01 21:41
Thank you Rayjolt I just notice maybe I'm wrong that it is not possible to share a post I mean each post-deployed on the website and it be published on facebook network :(

**Comment by rayjolt** [comment] 2017-11-01 23:30
Hello again Karoline. Hugo doesn't deal with the deployment of your website at all - it only generates the HTML for you. You can probably do this, but you will have to use a different tool or write the code yourself.

**Comment by Karolinehc** [comment] 2017-11-02 22:22
hello once again @rayjolt  :) I found this code and I inserted it on the folder "layouts" on "single html" there wasn't error but it neither works if you have an idea or advice that I could do I would appreciate that you tell me, please. Thank you @rayjolt 

{{ if .Site.Params.sharebuttons }}
                <div class="blog-share">
                Share this:
                <a class="twitter-share-button" href="https://twitter.com/intent/tweet?text=Read%20{{ .Title }}%20{{ .Permalink }}"
                onclick="window.open(this.href, 'twitter-share', 'width=550,height=235');return false;">
                <i class="fa fa-twitter"></i>
                <span class="hidden">Twitter</span>
                </a>
                <a class="icon-facebook" href="https://www.facebook.com/sharer/sharer.php?u={{ .Permalink }}"
                onclick="window.open(this.href, 'facebook-share','width=580,height=296');return false;">
                <i class="fa fa-facebook"></i>
                <span class="hidden">Facebook</span>
                </a>
                <a class="icon-pinterest" href="http://pinterest.com/pin/create/button/?url={{ .Permalink }}{{ if .Params.pinterestmedia }}&amp;media={{ .Site.BaseURL }}{{ .Params.pinterestmedia }}{{ end }}&amp;description={{ .Title | safeHTML}}"
                onclick="window.open(this.href, 'pinterest-share','width=580,height=296');return false;">
                <i class="fa fa-pinterest"></i>
                <span class="hidden">Pinterest</span>
                </a>
                <a class="icon-google-plus" href="https://plus.google.com/share?url={{ .Permalink }}"
                onclick="window.open(this.href, 'google-plus-share', 'width=490,height=530');return false;">
                <i class="fa fa-linkedin"></i>
                <span class="hidden">Google+</span>
                </a>
                </div>
            {{ end }}

**Comment by Karolinehc** [comment] 2017-11-02 22:28
hello @rayjolt  once again :) I found this code and I inserted it on "layouts" and "default single.html" there wasn't an error but neither it works if you have some advice or an idea I would appreciate that you tell me, thank you @rayjolt ! 

`{{ if .Site.Params.sharebuttons }}
                <div class="blog-share"> 
                Share this:
                <a class="twitter-share-button" href="https://twitter.com/intent/tweet?text=Read%20{{ .Title }}%20{{ .Permalink }}"
                onclick="window.open(this.href, 'twitter-share', 'width=550,height=235');return false;">
                <i class="fa fa-twitter"></i>
                <span class="hidden">Twitter</span>
                </a>
                <a class="icon-facebook" href="https://www.facebook.com/sharer/sharer.php?u={{ .Permalink }}"
                onclick="window.open(this.href, 'facebook-share','width=580,height=296');return false;">
                <i class="fa fa-facebook"></i>
                <span class="hidden">Facebook</span>
                </a>
                <a class="icon-pinterest" href="http://pinterest.com/pin/create/button/?url={{ .Permalink }}{{ if .Params.pinterestmedia }}&amp;media={{ .Site.BaseURL }}{{ .Params.pinterestmedia }}{{ end }}&amp;description={{ .Title | safeHTML}}"
                onclick="window.open(this.href, 'pinterest-share','width=580,height=296');return false;">
                <i class="fa fa-pinterest"></i>
                <span class="hidden">Pinterest</span>
                </a>
                <a class="icon-google-plus" href="https://plus.google.com/share?url={{ .Permalink }}"
                onclick="window.open(this.href, 'google-plus-share', 'width=490,height=530');return false;">
                <i class="fa fa-linkedin"></i>
                <span class="hidden">Google+</span>
                </a>
                </div>
            {{ end }}


`

**Comment by Karolinehc** [comment] 2017-11-02 22:31
`hello @rayjolt once again :) I found this code and I inserted it on "layouts" and "default single.html" there wasn't an error but neither it works if you have some advice or an idea I would appreciate that you tell me, thank you @rayjolt !

`{{ if .Site.Params.sharebuttons }}`
` <div class="default-share">
                Share this:
                <a class="twitter-share-button" href="https://twitter.com/intent/tweet?text=Read%20{{ .Title }}%20{{ .Permalink }}"
                onclick="window.open(this.href, 'twitter-share', 'width=550,height=235');return false;">
                <i class="fa fa-twitter"></i>
                <span class="hidden">Twitter</span>
                </a>
                <a class="icon-facebook" href="https://www.facebook.com/sharer/sharer.php?u={{ .Permalink }}"
                onclick="window.open(this.href, 'facebook-share','width=580,height=296');return false;">
                <i class="fa fa-facebook"></i>
                <span class="hidden">Facebook</span>
                </a>
                <a class="icon-pinterest" href="http://pinterest.com/pin/create/button/?url={{ .Permalink }}{{ if .Params.pinterestmedia }}&amp;media={{ .Site.BaseURL }}{{ .Params.pinterestmedia }}{{ end }}&amp;description={{ .Title | safeHTML}}"
                onclick="window.open(this.href, 'pinterest-share','width=580,height=296');return false;">
                <i class="fa fa-pinterest"></i>
                <span class="hidden">Pinterest</span>
                </a>
                <a class="icon-google-plus" href="https://plus.google.com/share?url={{ .Permalink }}"
                onclick="window.open(this.href, 'google-plus-share', 'width=490,height=530');return false;">
                <i class="fa fa-linkedin"></i>
                <span class="hidden">Google+</span>
                </a>
                </div>
            {{ end }}`

**Comment by Karolinehc** [comment] 2017-11-02 22:38
`hello @rayjolt once again :) :) I found this code and I inserted it on "layouts" and "default single.html" there wasn't an error but neither it works if you have some advice or an idea I would appreciate that you tell me, thank you @rayjolt !

{{ if .Site.Params.sharebuttons }}
<div class="blog-share"> Share this: 
<a class="twitter-share-button" href="https://twitter.com/intent/tweet?text=Read%20{{ .Title }}%20{{ .Permalink }}" 
onclick="window.open(this.href, 'twitter-share', 'width=550,height=235');return false;"> <i class="fa fa-twitter"></i> <span class="hidden">Twitter</span> </a> <a class="icon-facebook" href="https://www.facebook.com/sharer/sharer.php?u={{ .Permalink }}" 
onclick="window.open(this.href, 'facebook-share','width=580,height=296');return false;"> <i class="fa fa-facebook"></i> <span class="hidden">Facebook</span> </a> <a class="icon-pinterest" href="http://pinterest.com/pin/create/button/?url={{ .Permalink }}{{ if .Params.pinterestmedia }}&amp;media={{ .Site.BaseURL }}{{ .Params.pinterestmedia }}{{ end }}&amp;description={{ .Title | safeHTML}}" 
onclick="window.open(this.href, 'pinterest-share','width=580,height=296');return false;"> <i class="fa fa-pinterest"></i> <span class="hidden">Pinterest</span> </a> <a class="icon-google-plus" href="https://plus.google.com/share?url={{ .Permalink }}" 
onclick="window.open(this.href, 'google-plus-share', 'width=490,height=530');return false;"> <i class="fa fa-linkedin"></i> <span class="hidden">Google+</span> </a> </div> {{ end }}

**Comment by Karolinehc** [comment] 2017-11-02 22:40
`hello @rayjolt once again :) :) I found this code and I inserted it on "layouts" and "default single.html" there wasn't an error but neither it works if you have some advice or an idea I would appreciate that you tell me, thank you @rayjolt !
`{{ if .Site.Params.sharebuttons }}
                <div class="default-share">
                Share this:
                <a class="twitter-share-button" href="https://twitter.com/intent/tweet?text=Read%20{{ .Title }}%20{{ .Permalink }}"
                onclick="window.open(this.href, 'twitter-share', 'width=550,height=235');return false;">
                <i class="fa fa-twitter"></i>
                <span class="hidden">Twitter</span>
                </a>
                <a class="icon-facebook" href="https://www.facebook.com/sharer/sharer.php?u={{ .Permalink }}"
                onclick="window.open(this.href, 'facebook-share','width=580,height=296');return false;">
                <i class="fa fa-facebook"></i>
                <span class="hidden">Facebook</span>
                </a>
                <a class="icon-pinterest" href="http://pinterest.com/pin/create/button/?url={{ .Permalink }}{{ if .Params.pinterestmedia }}&amp;media={{ .Site.BaseURL }}{{ .Params.pinterestmedia }}{{ end }}&amp;description={{ .Title | safeHTML}}"
                onclick="window.open(this.href, 'pinterest-share','width=580,height=296');return false;">
                <i class="fa fa-pinterest"></i>
                <span class="hidden">Pinterest</span>
                </a>
                <a class="icon-google-plus" href="https://plus.google.com/share?url={{ .Permalink }}"
                onclick="window.open(this.href, 'google-plus-share', 'width=490,height=530');return false;">
                <i class="fa fa-linkedin"></i>
                <span class="hidden">Google+</span>
                </a>
                </div>
            {{ end }}

`

**Comment by Karolinehc** [comment] 2017-11-02 22:41
hello @rayjolt once again :) :) I found this code and I inserted it on "layouts" and "default single.html" there wasn't an error but neither it works if you have some advice or an idea I would appreciate that you tell me, thank you @rayjolt !
`{{ if .Site.Params.sharebuttons }}`
`<div class="blog-share">
                Share this:
                <a class="twitter-share-button" href="https://twitter.com/intent/tweet?text=Read%20{{ .Title }}%20{{ .Permalink }}"
                onclick="window.open(this.href, 'twitter-share', 'width=550,height=235');return false;">
                <i class="fa fa-twitter"></i>
                <span class="hidden">Twitter</span>
                </a>
                <a class="icon-facebook" href="https://www.facebook.com/sharer/sharer.php?u={{ .Permalink }}"
                onclick="window.open(this.href, 'facebook-share','width=580,height=296');return false;">
                <i class="fa fa-facebook"></i>
                <span class="hidden">Facebook</span>
                </a>
                <a class="icon-pinterest" href="http://pinterest.com/pin/create/button/?url={{ .Permalink }}{{ if .Params.pinterestmedia }}&amp;media={{ .Site.BaseURL }}{{ .Params.pinterestmedia }}{{ end }}&amp;description={{ .Title | safeHTML}}"
                onclick="window.open(this.href, 'pinterest-share','width=580,height=296');return false;">
                <i class="fa fa-pinterest"></i>
                <span class="hidden">Pinterest</span>
                </a>
                <a class="icon-google-plus" href="https://plus.google.com/share?url={{ .Permalink }}"
                onclick="window.open(this.href, 'google-plus-share', 'width=490,height=530');return false;">
                <i class="fa fa-linkedin"></i>
                <span class="hidden">Google+</span>
                </a>
                </div>
            {{ end }}
`

**Comment by rayjolt** [comment] 2017-11-06 15:01
This is getting out of the scope of hugo-multilingual-example, I think. Perhaps you could try browsing questions at https://stackoverflow.com/, and submitting one if you can't find a good answer. Best of luck in getting everything working.
